---
application:
  name: "lottsanook"
  project: "lottsanook"
  organization: "QoveryCommunity"
  publicly_accessible: true
  port: 80
routers:
- name: "main-lottsanook"
  routes:
  - application_name: "lottsanook"
    paths:
    - "/"
