---
application:
  name: "lottsanook"
  project: "lottsanook"
  organization: "QoveryCommunity"
  port: 8080
routers:
- name: "main-lottsanook"
  routes:
  - application_name: "lottsanook"
    paths:
    - "/*"
